version: 2.1

jobs:
  build-test:
    working_directory: ~/kalite
    docker:
      - image: circleci/python:2.7.17-stretch-node-browsers
    steps:
      - checkout
      - run: pip install -r requirements_sphinx.txt
      - run: pip install -e .
      - run:
          name: "Downgrade Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v6.9.5-linux-x64/bin/node
      - run: make assets
      - run: make docs
      - run: firefox -v
      - run: wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
      - run: gunzip -c geckodriver.tar.gz | tar xopf -
      - run: chmod +x geckodriver
      - run: sudo mv geckodriver /usr/local/bin
      - run: kalite start --traceback -v2
      - run: sleep 10s  # Necessary for server to be ready
      - run: kalite status
      - run: kalite stop --traceback -v2
      - run: coverage run bin/kalite manage test --bdd-only
      - run: coverage run bin/kalite manage test --no-bdd
      - run: bash <(curl -s https://codecov.io/bash)
      - run: npm install -g jshint
      - run: jshint kalite/*/static/js/*/
      - run:
          name: Upload CodeCov.io Data
          command: bash <(curl -s https://codecov.io/bash)
          when: always # Uploads code coverage results, pass or fail


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
